### PR TITLE
CMS a go-go

### LINKED ISSUE #162: Migrate to Gatsby / Netlify
Collection types:

* Press - Title, venue, date, summary, link
* Team member - Pic, name, Twitter, LinkedIn, Github, Keybase
* Advisor - Pic, name, Twitter, LinkedIn, Github, Keybase

### PR DESCRIPTION
**Pull request by ironng**
Hello, old sport...

This ports our site from Create React App to Gatsby + Netlify CMS.

Closes #162 

We've zhuzhed up this integration branch just a teeny bit by addressing some nits on the press page and hooking up the backend auth endpoints in the CMS config. (Relevant commits: eb6c28a, 07b68dc, ef0d44f)

### CODE REVIEW

**Comment by ironng** [comment]
@liz-shinn Here is the [preview](https://preview.keep.network/old-sport/)

**Comment by ironng** [comment]
@Shadowfiend I think we'll need to deploy the latest changes to the keep website backend to test if the admin is working correctly.

**Comment by Shadowfiend** [comment]
Went ahead and reran the Circle build so the whitepaper link works again :grimacing:

There's a weird thing I'm seeing in Safari + FF where if you follow a direct link to the press page (e.g., clicking on https://preview.keep.network/old-sport/press or on the press link in the footer), the header doesn't underline Press correctly.

**Comment by ironng** [comment]
>There's a weird thing I'm seeing in Safari + FF

@Shadowfiend I'm seeing that issue on FF + Safari for the preview as a well; however, I'm not able to reproduce it locally for those browsers. I think it is a peculiarity of the prefix builds. To apply the active state for the press page link, we're just using the `activeClassName` prop for [Gatsby's Link component](https://www.gatsbyjs.org/docs/gatsby-link/#add-custom-styles-for-the-currently-active-link). The relevant code bit is [here](https://github.com/keep-network/website/blob/40d8cc8bf3dfde107a5bb78160b69f27ecf72b90/src/components/Header.js#L4).

**Comment by Shadowfiend** [comment]
Ok cool. Worst comes worst it still happens post deploy we can diagnose it better then :)

**Comment by ironng** [comment]
@liz-shinn Thanks for your notes! I've addressed everything you mentioned except adjusting the nav menu height on scroll - I think we might need to tinker with that a bit more.

**Comment by Shadowfiend** [comment]
Re https://github.com/keep-network/website/commit/b49bf495a0c531c41a659099ffbd0742fe0238c7 I’ll note I’m a little curious as to why the state is stuck in the first place—it feels like the underlying link should never end up “active” since the page URL never changes—but not that interested in sleuthing it out right now lol.

**Pull request merged**
