### PR TITLE
Update team info and primer

### PR DESCRIPTION
**Pull request by ironng**
- Adds Piotr and Jakub as new team members
- Adds LinkedIn link for Elizaveta
- Updates Hope's title
- Updates primer to latest version

### CODE REVIEW

**Comment by Shadowfiend** [comment]
@elizapetrovska @ironng the business primer's content looks like it's right aligned right now 🙊 Can we fix that?

**Comment by elizapetrovska** [comment]
[keepBusinessPrimer june 18.pdf](https://github.com/keep-network/website/files/2116025/keepBusinessPrimer.june.18.pdf)

**Comment by ironng** [comment]
Updated!

**Comment by Shadowfiend** [comment]
Missed this in my first pass… In the page that starts with Prashanth, the content starts way too close to the top margin. Not sure what that margin is supposed to be, but it's probably good to base it on the other pages.

Sorry for not noticing the first time, I know it's a pain to keep updating it :(

**Comment by elizapetrovska** [comment]
[keepBusinessPrimer june 20.pdf](https://github.com/keep-network/website/files/2121121/keepBusinessPrimer.june.20.pdf)

No problem, you are right. Have a look if this is enough

**Comment by ironng** [comment]
Let me know if it looks good, then I will update it! :)

**Comment by Shadowfiend** [comment]
It's still a bit tight, but let's roll with it!

**Comment by Shadowfiend** [comment]
Ok, let's do it!

**Comment by Shadowfiend** [comment]
Deployed!

**Pull request merged**
