### PR TITLE
Fix(UI)/SRT-87: UI feedback update 3

### PR DESCRIPTION
**Pull request by FrozenIce0617**
Ticket: [[SRT-87](https://scalio.atlassian.net/browse/SRT-87)]

- Logo: Logo on mobile is pushed down by banner
- Header: Remove drop-shadow container around all sub-navigation items on mobile
- Team page: Team member name's line-height to be smaller
- Info page: Tbtc “check it out” button to be full-width on mobile
- Stake page: Logos for staking providers to be more margin on both of Desktop and Mobile screen
- Home page: Email validation error message shows under the input and update the success message content for subsribed
- Join and Info page: minor changes for image showing as fit on mobile

### CODE REVIEW

**Review by micahjlucas — CHANGES_REQUESTED** [review]
Placing on hold until latest comments are addressed.

**Review by micahjlucas — APPROVED** [review]
Approved by Liz as well.

**Comment by Battenfield** [comment]
set to merge & deploy tomorrow

**Review by Battenfield — APPROVED** [review]
🚀

**Pull request merged**
