### PR TITLE
Magical Emms: Add Markus and Marcin to site + primer

### LINKED ISSUE #82: update primer with Markus and Marcin
[keepBusinessPrimer 31.10.2018 pdf.pdf](https://github.com/keep-network/website/files/2535116/keepBusinessPrimer.31.10.2018.pdf.pdf)

### LINKED ISSUE #83: Add Markus and Marcin to the website
1. fix-portrait

Markus Fix

https://twitter.com/lispmeister
https://www.linkedin.com/in/lispmeister/
https://github.com/lispmeister
https://keybase.io/lispmeister

2. 

marcin

Marcin Pawlowski

https://twitter.com/mpspp
https://www.linkedin.com/in/mpspp/
https://keybase.io/mpp
https://github.com/madxor

### PR DESCRIPTION
**Pull request by Shadowfiend**
We do as we say!

Closes #82, closes #83.

### CODE REVIEW

**Comment by madxor** [comment]
That primer is an old one!

**Comment by mhluongo** [comment]
Good catch- I think they just forgot the date change :sob:

**Comment by mhluongo** [comment]
#82 has a newer version @Shadowfiend

**Comment by Shadowfiend** [comment]
I… Just downloaded the one in 82 when I created this PR. O.o lol.

**Comment by Shadowfiend** [comment]
Ah, that was before the update lol.

**Comment by Shadowfiend** [comment]
:rocket:

**Pull request merged**
