### PR TITLE
Update team and advisors

### PR DESCRIPTION
**Pull request by ironng**
- Added Aaron to the team
- Updated John Packel's title

screen shot 2018-10-17 at 3 57 15 pm
screen shot 2018-10-17 at 3 57 43 pm

Closes keep-network/website-backend#11, closes keep-network/website-backend#12.

### CODE REVIEW

**Comment by Shadowfiend** [comment]
Two tidbits:
- Do we need to reference any issues here?
- Going to hold this until Laura's back as I believe she had some content she wanted to ship out alongside these updates.

**Comment by ironng** [comment]
I wasn’t sure if I should recreate the issues from the other repo here? 😅

This PR addresses:
- https://github.com/keep-network/website-backend/issues/11
- https://github.com/keep-network/website-backend/issues/12

**Comment by Shadowfiend** [comment]
I'm curious to see if GH handles this… Going to update the PR description and see what happens 🙈

**Comment by Shadowfiend** [comment]
'Tworked!

**Comment by ironng** [comment]
Ah I thought you could put “Closes” anywhere in the PR, but it has to be in the description? Thank you for editing! :)

**Comment by Shadowfiend** [comment]
I think you can, but you have to reference the issue with the syntax `#..` or, for cross-repo, `<org>/<repo>#..`, rather than using links. Not certain though.

**Comment by clp16** [comment]
Aaron O'hearn was asking if this could be merged. There aren't any updates other than Markus and Marcin for pictures that I'm aware of. Were we waiting on clarification on anything else? If so, let me know and I'll hunt it down. @Shadowfiend @ironng

**Comment by Shadowfiend** [comment]
See my note [here](https://github.com/keep-network/website/pull/81#issuecomment-431019002) regarding Laura wanting to ship content alongside this update. Happy to merge if we want to go for it.

**Comment by ironng** [comment]
Do you want me to get Markus, Marcin, and the security upgrades in here with this PR too? Or I can wait until this is merged and open a separate one.

**Comment by Shadowfiend** [comment]
Let's do a separate PR since those can go out independently from this @ironng.

**Comment by clp16** [comment]
Laura said she's all set. We're good to go. Letting Aaron know this update is coming soon.

**Comment by Shadowfiend** [comment]
K, merging and shipping!

**Pull request merged**
