### PR TITLE
#220 Token dashboard cta

### PR DESCRIPTION
**Pull request by cpham**
#220 adding token dashboard module to homepage

### CODE REVIEW

**Review by Shadowfiend — APPROVED** [review]
High-level this looks good to me. Put out a quick question on whether we want to adjust the verbiage before landing, so will hold until I get an answer. 

Also flagging: the iPad/screenshot seems a bit low-res. Do we have a 3x version we can use? cc @liz-shinn

**Comment by Shadowfiend** [comment]
> Preview uploaded to https://preview.keep.network/token-dashboard-cta/.

Note to self: would probably be good to append a `?<timestamp>` to the end to cache-bust the previews here.

**Comment by Shadowfiend** [comment]
A'ight let's do this thing.

**Comment by liz-shinn** [comment]
Yeah I was wondering if that image was high quality enough it looked fuzzy in the screenshot in FD. I've updated it:

rewards-page

**Pull request merged**
