### PR TITLE
Update to latest primer

### LINKED ISSUE #102: Update Business Primer by Fixing the "confidential" and "https" Bits and Upload to the website

### PR DESCRIPTION
**Pull request by ironng**
Closes #102

### CODE REVIEW

**Comment by elizapetrovska** [comment]
What are the additional steps needed for the Primer to be up on the website please?

**Comment by elizapetrovska** [comment]
[Keep-Business-Primer_2019-3-26.pdf](https://github.com/keep-network/website/files/3014131/Keep-Business-Primer_2019-3-26.pdf)

**Comment by elizapetrovska** [comment]
Guys, are we planning to upload it to the website?

**Comment by ironng** [comment]
@elizapetrovska is this primer you just listed different from the one Michael provided?

**Comment by elizapetrovska** [comment]
No, it is the same. Might not understand the process fully, but I don't believe it is up on the website?

**Comment by ironng** [comment]
This was merged into the code, but still not deployed live then. @Shadowfiend can you deploy when you get a chance please? 🙏 

On a side note, should we tackle #16 sometime?

**Comment by elizapetrovska** [comment]
@Shadowfiend , is there a chance to have it up on the website today?

**Comment by Shadowfiend** [comment]
Ummm yeah. I forgot this doesn't auto-deploy.

We should definitely tackle that issue lolol. It's probably not even that hard.

**Comment by Shadowfiend** [comment]
All done!

**Comment by elizapetrovska** [comment]
🎉 🎊

**Pull request merged**
