### PR TITLE
Update Pages “press”

### PR DESCRIPTION
**Pull request by liz-shinn**
Automatically generated by Netlify CMS

### CODE REVIEW

**Comment by liz-shinn** [comment]
This update changes the media kit files by adding: 

- Keep logo: mint versions of the logo in SVG, PDF, and PNG
- Keep K mark: black and mint versions in SVG, PDF, and PNG
- token symbol in black and in white in PNG
- Keep Media Guide PDF

**Comment by liz-shinn** [comment]
It's not showing in the preview so not sure it went through, but also would like to updated the text below Media Kit:

Screen Shot 2020-08-13 at 6 16 27 PM

**Comment by ironng** [comment]
@liz-shinn It's been on my todos to set up configure the visual previews for all the pages. 😅 I should probably make an actual issue for it so it's tracked.

In the future, you can always check out the live preview for PRs at `https://preview.keep.network/<name-of-the-pr-branch>`, so the current preview is [here](https://preview.keep.network/cms/pages/press/press/). 

Looks like the newspaper logo broke? To update the asset, you'll need to update the "file" field in "Download Button" rather than the image asset for the "Icon".

**Comment by ironng** [comment]
@liz-shinn I went ahead and fixed the issue and removed the old media kit

**Comment by liz-shinn** [comment]
Thanks @ironng ! 💯 

>Maybe in the future we should make a separate field for the actual kit or rename the "file" field for better clarity?

This seems like a good idea to me! We could rename it "media kit file" or something?

**Pull request merged**
